Organize code
coralogix/prometheus-alert-readiness pull request #3
Opened 2021-02-23 18:44 UTC by ari-becker

2021-02-23 18:57 UTC, oded-dd requested changes
Looks much much better. 
I would also add an example directory. with the Unready alert for each of the use cases. 
It will provide the entire loop for any developer/ops who wants to use it

2021-02-23 18:57 UTC, oded-dd commented on README.md
> +underr-replicated, but not unavailable) state. The more mature approach is to
underr --> under

2021-02-23 18:57 UTC, oded-dd commented on README.md
> +
Use case 2 - streaming ... Kafka mechanism + lag (translated to business SLO/SLI)

2021-02-23 18:57 UTC, oded-dd commented on README.md
> +
Use case 3 - disruptive behavior - TME/SalesEngineer can run an important demo and block the upgrade process ...

2021-02-23 18:58 UTC, ari-becker commented on README.md
> +underr-replicated, but not unavailable) state. The more mature approach is to
fixed already

2021-03-01 09:01 UTC, oded-dd approved these changes

2021-03-01 09:02 UTC, merged